### ISSUE TITLE
wavelength range for extinction laws

### ISSUE THREAD

**Issue by mgennaro** [spacetelescope/synphot_refactor#218] opened 2019-09-05 16:29 UTC
I have found the hard way that the "Milky Way average" extinction law is defined only up to 22222.223 angstrom.

As a consequence, it is impossible to produce "effstim" for nircam long wavelength bandpasses (>25000 angstroms).

Other extinction laws "from models" (e.g. mwrv21) extend up to 50k angstrom.

I assume that all these models are realization of the cardelli extinction law for different values of rv, thus the inconsistency could be solved. 

At the same time, it owuld be good to have an option to use the cardelli, or fitzpatrick laws for any value of the Rv parameter. Right now, to do so, one has to write such laws to a file and use the from_file method to create a synphot law.  

Is there a way to integrate something like this:

https://extinction.readthedocs.io/en/latest/

into the synphot extinction law part? Maybe specutils is doing something similar?

**Comment by pllim** [comment] 2019-09-05 16:48
This issue is a duplicate of #132 . Let's continue the discussion over there.

In the short term, I don't have time to do this, but nothing stops you from opening a pull request. :grimacing:

**Closed by pllim** 2019-09-05 16:48 UTC
